security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    %security.doc_user%: { password: %security.doc_password%, roles: 'ROLE_DEVELOPER' }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error))/
            security: false

        doc:
            pattern: ^/$
            http_basic:
                realm: "Secured area"

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                login_path: /oauth/v2/auth_login
                check_path: /oauth/v2/auth_check
            logout:
                path:   /oauth/v2/auth_logout
                target: /oauth/v2/auth_login
            anonymous:    true

        api:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true
#            anonymous:  false # can be omitted as its default value

    access_control:
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }
#        - { path: ^/oauth/v2/auth_reset.*$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
