parameters:
    loanapound.security.oauth_event_listener.class: AppBundle\EventListener\OAuthEventListener

services:
    loanapound.security.oauth_event_listener:
        class: %loanapound.security.oauth_event_listener.class%
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }

